### Option: Plugins.OPCUA.System.Path
#	Path to external plugin executable.
#
# Mandatory: yes
# Default:
# Plugins.OPCUA.System.Path=

### Option: Plugins.OPCUA.Timeout
#	The maximum amount of time in seconds to wait for an OPC UA server to respond to requests.
#
# Mandatory: no
# Range: 1-30
# Default:
# Plugins.OPCUA.Timeout=<Global timeout>

### Option: Plugins.OPCUA.Sessions.*.Uri
#	OPC UA endpoint URI to connect. "*" should be replaced with a session name.
#
# Mandatory: no
# Range:
#   Must match the URI format.
#   Supported scheme: "opc.tcp".
# Default: opc.tcp://localhost:4840
# Plugins.OPCUA.Sessions.*.Uri=

### Option: Plugins.OPCUA.Sessions.*.User
#	Username for session connection. "*" should be replaced with a session name.
#	If omitted, anonymous authentication is used.
#
# Mandatory: no
# Default:
# Plugins.OPCUA.Sessions.*.User=

### Option: Plugins.OPCUA.Sessions.*.Password
#	Password for session connection. "*" should be replaced with a session name.
#
# Mandatory: no
# Range: Max 512 characters.
# Default:
# Plugins.OPCUA.Sessions.*.Password=

### Option: Plugins.OPCUA.Sessions.*.SecurityMode
#	Security mode for session connection. "*" should be replaced with a session name.
#
# Mandatory: no
# Range: None, Sign, SignAndEncrypt.
# Default: None
# Plugins.OPCUA.Sessions.*.SecurityMode=

### Option: Plugins.OPCUA.Sessions.*.SecurityPolicy
#	Security policy for session connection. "*" should be replaced with a session name.
#
# Mandatory: no
# Range: None, Basic128Rsa15, Basic256, Basic256Sha256, Aes128_Sha256_RsaOaep, Aes256_Sha256_RsaPss, or full Security Policy URI.
# Default: None
# Plugins.OPCUA.Sessions.*.SecurityPolicy=

### Option: Plugins.OPCUA.Sessions.*.CertFile
#	Full pathname of client certificate file (.crt or .pem). "*" should be replaced with a session name.
#
# Mandatory: no
# Default:
# Plugins.OPCUA.Sessions.*.CertFile=

### Option: Plugins.OPCUA.Sessions.*.KeyFile
#	Full pathname of client private key file (.key or .pem). "*" should be replaced with a session name.
#
# Mandatory: no
# Default:
# Plugins.OPCUA.Sessions.*.KeyFile=

### Option: Plugins.OPCUA.Default.Uri
#	OPC UA endpoint URI to connect. Default value used if no other is specified.
#
# Mandatory: no
# Range:
#   Must match the URI format.
#   Supported scheme: "opc.tcp".
# Default: opc.tcp://localhost:4840
# Plugins.OPCUA.Default.Uri=

### Option: Plugins.OPCUA.Default.User
#	Username for connection. Default value used if no other is specified.
#	If omitted, anonymous authentication is used.
#
# Mandatory: no
# Default:
# Plugins.OPCUA.Default.User=

### Option: Plugins.OPCUA.Default.Password
#	Password for connection. Default value used if no other is specified.
#
# Mandatory: no
# Range: Max 512 characters.
# Default:
# Plugins.OPCUA.Default.Password=

### Option: Plugins.OPCUA.Default.SecurityMode
#	Security mode for connection. Default value used if no other is specified.
#
# Mandatory: no
# Range: None, Sign, SignAndEncrypt.
# Default: None
# Plugins.OPCUA.Default.SecurityMode=

### Option: Plugins.OPCUA.Default.SecurityPolicy
#	Security policy for connection. Default value used if no other is specified.
#
# Mandatory: no
# Range: None, Basic128Rsa15, Basic256, Basic256Sha256, Aes128_Sha256_RsaOaep, Aes256_Sha256_RsaPss, or full Security Policy URI.
# Default: None
# Plugins.OPCUA.Default.SecurityPolicy=

### Option: Plugins.OPCUA.Default.CertFile
#	Full pathname of client certificate file (.crt or .pem). Default value used if no other is specified.
#
# Mandatory: no
# Default:
# Plugins.OPCUA.Default.CertFile=

### Option: Plugins.OPCUA.Default.KeyFile
#	Full pathname of client private key file (.key or .pem). Default value used if no other is specified.
#
# Mandatory: no
# Default:
# Plugins.OPCUA.Default.KeyFile=
